# MACOSX_SDK_VERSION:       # [osx and x86_64]
#   - 13.0                  # [osx and x86_64]
# MACOSX_DEPLOYMENT_TARGET: # [osx and x86_64]
#   - 13.0                  # [osx and x86_64]
# macos_min_version:        # [osx and x86_64]
#   - 13.0                  # [osx and x86_64]
# CONDA_BUILD_SYSROOT:      # [osx and x86_64]
#   - /Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk  # [osx and x86_64]
