# Based on recipes from birdhouse and anaconda channel.

{% set name = "openjdk" %}
{% set version = "21.0.11" %}
{% set intellij_build = "1163.116" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-{{ version }}-osx-aarch64-b{{ intellij_build }}.tar.gz                   # [osx and arm64]
    fn: jbrsdk-{{ version }}-osx-aarch64-b{{ intellij_build }}.tar.gz                                                                        # [osx and arm64]
    sha256: ff2d12e6cf6b2f9d7793b8b6596afe413bdd4074fbfc91d9a36f379df61df182                                                                 # [osx and arm64]
  - url: https://cache-redirector.jetbrains.com/intellij-jbr/jbr_jcef-{{ version }}-osx-aarch64-b{{ intellij_build }}.tar.gz                 # [osx and arm64]
    fn: jbr_jcef-{{ version }}-osx-aarch64-b{{ intellij_build }}.tar.gz                                                                      # [osx and arm64]
    sha256: 1f6835ee1445c28c1093e421a7c2f7e950aed5b632febf728778438fd078ab3c                                                                 # [osx and arm64]
  - url: https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-{{ version }}-linux-x64-b{{ intellij_build }}.tar.gz                     # [linux and not aarch64]
    fn: jbrsdk-{{ version }}-linux-x64-b{{ intellij_build }}.tar.gz                                                                          # [linux and not aarch64]
    sha256: 097bf328b5bf5a236c095b8c8e5204c0eda91e5baa06b37383a7754b10671d8b                                                                 # [linux and not aarch64]
  - url: https://cache-redirector.jetbrains.com/intellij-jbr/jbr_jcef-{{ version }}-linux-x64-b{{ intellij_build }}.tar.gz                   # [linux and not aarch64]
    fn: jbr_jcef-{{ version }}-linux-x64-b{{ intellij_build }}.tar.gz                                                                        # [linux and not aarch64]
    sha256: 29bc13ce14b7ddb25cc03516c7d941a9c9ad6cdc5424b3e61087d194819fb483                                                                 # [linux and not aarch64]
  - url: https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-{{ version }}-linux-aarch64-b{{ intellij_build }}.tar.gz                 # [linux and aarch64]
    fn: jbrsdk-{{ version }}-linux-aarch64-b{{ intellij_build }}.tar.gz                                                                      # [linux and aarch64]
    sha256: 21ff925581865d97da97df5c8bdb2ab320dbf6aa609a6556efe3c9a7a7c62db2                                                                 # [linux and aarch64]
  - url: https://cache-redirector.jetbrains.com/intellij-jbr/jbr_jcef-{{ version }}-linux-aarch64-b{{ intellij_build }}.tar.gz               # [linux and aarch64]
    fn: jbr_jcef-{{ version }}-linux-aarch64-b{{ intellij_build }}.tar.gz                                                                    # [linux and aarch64]
    sha256: 159d5f32a45461a76ba67803a4b8f456398ec80729534bb77603eb5fb048d610                                                                 # [linux and aarch64]
  - url: https://github.com/dejavu-fonts/dejavu-fonts/releases/download/version_2_37/dejavu-fonts-ttf-2.37.zip                               # [linux]
    sha256: 7576310b219e04159d35ff61dd4a4ec4cdba4f35c00e002a136f00e96a908b0a                                                                 # [linux]
    folder: fonts                                                                                                                            # [linux]
  - url: https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-{{ version }}-windows-x64-b{{ intellij_build }}.tar.gz                   # [win64]
    fn: jbrsdk-{{ version }}-windows-x64-b{{ intellij_build }}.tar.gz                                                                        # [win64]
    sha256: a3b01a47e67207722064c136616a3c0529e0dc96e17d0d5e44a0e8b4a92c57e7                                                                 # [win64]
  - url: https://cache-redirector.jetbrains.com/intellij-jbr/jbr_jcef-{{ version }}-windows-x64-b{{ intellij_build }}.tar.gz                 # [win64]
    fn: jbr_jcef-{{ version }}-windows-x64-b{{ intellij_build }}.tar.gz                                                                      # [win64]
    sha256: 40a305663ded81fd49f11bb314253026df6a54b18e919bea2fc184c8f72ef23b                                                                 # [win64]

build:
  number: 0
  ignore_run_exports:
    - dbus               # [linux]
    - expat              # [linux]
    - freetype           # [linux]
    - libxcb             # [linux]
    - zlib               # [osx]
    - glib               # [linux]
  missing_dso_whitelist:
    - $RPATH/libz.so.1
    - $RPATH/libjli.so
    - $RPATH/libjvm.so
    - $RPATH/libgobject-2.0.so.0
    - $RPATH/libglib-2.0.so.0
    - $RPATH/libnss3.so
    - $RPATH/libdrm.so.2
    - $RPATH/libgbm.so.1
    - $RPATH/libnssutil3.so
    - $RPATH/libsmime3.so
    - $RPATH/libnspr4.so
    - $RPATH/libatk-1.0.so.0
    - $RPATH/libatk-bridge-2.0.so.0
    - $RPATH/libgio-2.0.so.0
    - $RPATH/libxkbcommon.so.0
    - $RPATH/libX11.so.6
    - $RPATH/libXcomposite.so.1
    - $RPATH/libXdamage.so.1
    - $RPATH/libXext.so.6
    - $RPATH/libXfixes.so.3
    - $RPATH/libXrandr.so.2
    - $RPATH/libasound.so.2
    - $RPATH/libcups.so.2
    - $RPATH/libatspi.so.0
    - $RPATH/libxshmfence.so.1
    - $RPATH/libjawt.so
    - $RPATH/libXrender.so.1
    - $RPATH/libXtst.so.6
    - $RPATH/libXi.so.6
    - $RPATH/libXxf86vm.so.1
    - $RPATH/libXcursor.so.1
    - $RPATH/libstdc++.so.6
    - $RPATH/libudev.so.1               # [linux]
    - $RPATH/libjvm.dylib               # [osx]
    - $RPATH/libjawt.dylib              # [osx]
    - $RPATH/libpangoft2-1.0.so.0       # [linux and aarch64]
    - $RPATH/libgtk-x11-2.0.so.0        # [linux and aarch64]
    - $RPATH/libgdk-x11-2.0.so.0        # [linux and aarch64]
    - $RPATH/libgdk_pixbuf-2.0.so.0     # [linux and aarch64]
    - $RPATH/libgthread-2.0.so.0        # [linux and aarch64]
    - $RPATH/ld-linux-x86-64.so.2       # [linux and aarch64]
    - $RPATH/libgtk-3.so.0              # [linux and aarch64]
    - $RPATH/libgdk-3.so.0              # [linux and aarch64]
    - $RPATH/libavcodec-ffmpeg.so.56    # [linux and aarch64]
    - $RPATH/libavformat-ffmpeg.so.56   # [linux and aarch64]
    - $RPATH/libGL.so.1                 # [linux and aarch64]
    - $RPATH/libgmodule-2.0.so.0        # [linux and aarch64]
    - /*/*/*/*/*/*/*/Frameworks/JavaNativeFoundation.framework/JavaNativeFoundation       # [osx and arm64]
    - Library\bin\VCRUNTIME140.dll        # [win]
    - Library\bin\VCRUNTIME140_1.dll      # [win]
    - Library\bin\bin\VCRUNTIME140.dll    # [win]
    - Library\bin\bin\VCRUNTIME140_1.dll  # [win]
    - Library\bin\MSVCP140.dll            # [win]
    - Library\bin\bin\MSVCP140.dll        # [win]
    - $RPATH/jvm.dll                      # [win]
    - $RPATH/libcef.dll                   # [win]
    - $RPATH/chrome_elf.dll               # [win]
    - $RPATH/api-ms-win-core-winrt-string-l1-1-0.dll  # [win]
    - $RPATH/api-ms-win-core-realtime-l1-1-1.dll      # [win]
    - $RPATH/api-ms-win-core-winrt-l1-1-0.dll         # [win]
    - $RPATH/api-ms-win-shcore-scaling-l1-1-1.dll     # [win]
    - $RPATH/api-ms-win-power-base-l1-1-0.dll         # [win]
    - $RPATH/api-ms-win-power-setting-l1-1-0.dll      # [win]
    - $RPATH/libwayland-client.so.0
    - $RPATH/libwayland-cursor.so.0

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - zip                      # [linux]
  host:
    - cairo {{ cairo }}        # [linux]
    - dbus {{ dbus }}          # [linux]
    - expat {{ expat }}        # [linux]
    - freetype {{ freetype }}  # [linux]
    - glib {{ glib }}          # [linux]
    - libxcb {{ libxcb }}      # [linux]
    - pango {{ pango }}        # [linux]
    - zlib {{ zlib }}          # [unix]
  run:
    - cairo                    # [linux]
    - dbus                     # [linux]
    - expat                    # [linux]
    - freetype                 # [linux]
    - glib                     # [linux]
    - libxcb                   # [linux]
    - pango                    # [linux]
 
test:
  requires:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  files:
    - test-jni     # [not win]
    - test-jni.sh  # [not win]
    - test-nio

about:
  home: https://github.com/JetBrains/JetBrainsRuntime
  license: GPL-2.0-only
  license_family: GPL
  license_url: "https://raw.githubusercontent.com/JetBrains/JetBrainsRuntime/refs/tags/jdk-21+35/LICENSE"
  summary: The JetBrains Runtime OpenJDK build.
  description: |
    JetBrains Runtime is a runtime environment for running
    IntelliJ Platform based products on Windows, Mac OS X, and Linux
  dev_url: https://github.com/JetBrains/JetBrainsRuntime
  doc_url: https://openjdk.org/guide/

extra:
  recipe-maintainers:
    - johanneskoester
    - mingwandroid
    - sodre
