# Based on recipes from birdhouse and anaconda channel.

{% set name = "openjdk" %}
{% set version = "8.0.121" %}
{% set zulu_build = "8.20.0.5" %}
{% set build_number = 0 %}
{% set md5_linux = "e5f4b1d997e50ffe4998c68c8ec45403" %}
{% set md5_osx = "87cbe3789cba2851bd3a93c28a1b1672" %}
{% set md5_win = "89ea67c5966a44627809d9a46a2f3b25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-zulu{{ zulu_build }}-{{ version }}.tar.gz  # [linux64]
  fn: {{ name }}-zulu{{ zulu_build }}-{{ version }}.zip  # [osx or win64]
  url: http://cdn.azul.com/zulu/bin/zulu{{ zulu_build }}-jdk{{ version }}-linux_x64.tar.gz  # [linux64]
  url: http://cdn.azul.com/zulu/bin/zulu{{ zulu_build }}-jdk{{ version }}-macosx_x64.zip  # [osx]
  url: http://cdn.azul.com/zulu/bin/zulu{{ zulu_build }}-jdk{{ version }}-win_x64.zip  # [win64]
  md5: {{ md5_linux }}  # [linux64]
  md5: {{ md5_osx }}  # [osx]
  md5: {{ md5_win }}  # [win64]

build:
  number: {{ build_number }}
  skip: true  # [win32 or linux32]
  string: zulu{{ zulu_build }}_{{ build_number }}
  track_features:
    - openjdk
  rpath:
    - lib
    - jre/lib

requirements:
  build:
    - curl


test:
  files:
    - test-jni  # [not win]
    - test-jni.sh  # [not win]
    - test-nio
  commands:
    - java -version
    - ./test-jni.sh  # [not win]
    - javac test-nio/*.java
    - java -classpath test-nio TestFilePaths $PREFIX/jre file://./test-nio/TestFilePaths.java  # [unix]
    - java -classpath test-nio TestFilePaths %PREFIX%\jre  # [win]
    - conda inspect linkages -p ${PREFIX} openjdk  # [linux]
    - conda inspect objects -p ${PREFIX} openjdk  # [osx]

about:
  home: https://www.azul.com/products/zulu/
  license: GPLv2
  summary: The Zulu OpenJDK build.
  description: |
    Zulu OpenJDK is an open source build of the Java JDK.

extra:
  recipe-maintainers:
    - johanneskoester
    - sodre
