# Based on recipes from birdhouse and anaconda channel.

{% set name = "openjdk" %}
{% set version = "21.0.6" %}
{% set intellij_build = "895.97" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-{{ version }}-osx-x64-b{{ intellij_build }}.tar.gz                       # [osx and not arm64]]
    fn: jbrsdk-{{ version }}-osx-x64-b{{ intellij_build }}.tar.gz                                                                            # [osx and not arm64]
    sha256: d872b655624d173edf576873a840c3d9c5b6cbf5184c93d51d916341749148cd                                                                 # [osx and not arm64]
  - url: https://cache-redirector.jetbrains.com/intellij-jbr/jbr_jcef-{{ version }}-osx-x64-b{{ intellij_build }}.tar.gz                     # [osx and not arm64]
    fn: jbr_jcef-{{ version }}-osx-x64-b{{ intellij_build }}.tar.gz                                                                          # [osx and not arm64]
    sha256: 0c0e081cba37ad890dc02ac744025925f9852cd0aa97f393304f7682ad721c58                                                                 # [osx and not arm64]
  - url: https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-{{ version }}-osx-aarch64-b{{ intellij_build }}.tar.gz                   # [osx and arm64]
    fn: jbrsdk-{{ version }}-osx-aarch64-b{{ intellij_build }}.tar.gz                                                                        # [osx and arm64]
    sha256: 9df625d6f7a8b33236d4b8c4796c58f90f6b76c57b4c4a0a46c47fe2e88e3f17                                                                 # [osx and arm64]
  - url: https://cache-redirector.jetbrains.com/intellij-jbr/jbr_jcef-{{ version }}-osx-aarch64-b{{ intellij_build }}.tar.gz                 # [osx and arm64]
    fn: jbr_jcef-{{ version }}-osx-aarch64-b{{ intellij_build }}.tar.gz                                                                      # [osx and arm64]
    sha256: 53a8d285e288ea827d87f5de5556843570a8081a46fdad0c3357445787f0dcb7                                                                 # [osx and arm64]
  - url: https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-{{ version }}-linux-x64-b{{ intellij_build }}.tar.gz                     # [linux and not aarch64]
    fn: jbrsdk-{{ version }}-linux-x64-b{{ intellij_build }}.tar.gz                                                                          # [linux and not aarch64]
    sha256: 0d253d7995c4767e0c3e1ce090f0497b8f74e4a0240001695102690f64d18397                                                                 # [linux and not aarch64]
  - url: https://cache-redirector.jetbrains.com/intellij-jbr/jbr_jcef-{{ version }}-linux-x64-b{{ intellij_build }}.tar.gz                   # [linux and not aarch64]
    fn: jbr_jcef-{{ version }}-linux-x64-b{{ intellij_build }}.tar.gz                                                                        # [linux and not aarch64]
    sha256: d0f1c9979e5ce97f942de6fe8bacd641aa6be5f204eedd00cd55e3b1ebd9ea48                                                                 # [linux and not aarch64]
  - url: https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-{{ version }}-linux-aarch64-b{{ intellij_build }}.tar.gz                 # [linux and aarch64]
    fn: jbrsdk-{{ version }}-linux-aarch64-b{{ intellij_build }}.tar.gz                                                                      # [linux and aarch64]
    sha256: a5e35916ab77f86a1d903850fc62560fc5c3fd1933b1cfbd1eb06d39f68ffba5                                                                 # [linux and aarch64]
  - url: https://cache-redirector.jetbrains.com/intellij-jbr/jbr_jcef-{{ version }}-linux-aarch64-b{{ intellij_build }}.tar.gz                    # [linux and aarch64]
    fn: jbr_jcef-{{ version }}-linux-aarch64-b{{ intellij_build }}.tar.gz                                                                         # [linux and aarch64]
    sha256: df21732145817795e4d77c94690f54b9d29ab73995a4dc0c89313199aa14eea1                                                                 # [linux and aarch64]
  - url: https://github.com/dejavu-fonts/dejavu-fonts/releases/download/version_2_37/dejavu-fonts-ttf-2.37.zip                               # [linux]
    sha256: 7576310b219e04159d35ff61dd4a4ec4cdba4f35c00e002a136f00e96a908b0a                                                                 # [linux]
    folder: fonts                                                                                                                            # [linux]
  - url: https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-{{ version }}-windows-x64-b{{ intellij_build }}.tar.gz                   # [win64]
    fn: jbrsdk-{{ version }}-windows-x64-b{{ intellij_build }}.tar.gz                                                                        # [win64]
    sha256: 1cc76557ae6df315c9487e067f54b109a28a47f846b8238c1e313bea4e4b5c07                                                                 # [win64]
  - url: https://cache-redirector.jetbrains.com/intellij-jbr/jbr_jcef-{{ version }}-windows-x64-b{{ intellij_build }}.tar.gz                 # [win64]
    fn: jbr_jcef-{{ version }}-windows-x64-b{{ intellij_build }}.tar.gz                                                                      # [win64]
    sha256: ace0a8e434ca1161f7968588e1efa4f8a408493bf74f13886f1cf51dc6e65083                                                                 # [win64]

build:
  number: 0
  # openjdk 21.0.6 is not currently supported on ppc64le or s390x.
  # openjdk 11.0.13 requires GLIBC_2.27 on aarch64, but currently is available GLIBC_2.26.
  skip: True  # [ppc64le or s390x]
  ignore_run_exports:
    # - cairo              # [linux and aarch64]
    - dbus               # [linux]
    - expat              # [linux]
    - freetype           # [linux]
    - libxcb             # [linux]
    # - pango              # [linux and aarch64]
    - zlib               # [osx]
    - glib               # [linux]
  missing_dso_whitelist:
    - $RPATH/libz.so.1
    - $RPATH/libjli.so
    - $RPATH/libjvm.so
    - $RPATH/libgobject-2.0.so.0
    - $RPATH/libglib-2.0.so.0
    - $RPATH/libnss3.so
    - $RPATH/libdrm.so.2
    - $RPATH/libgbm.so.1
    - $RPATH/libnssutil3.so
    - $RPATH/libsmime3.so
    - $RPATH/libnspr4.so
    - $RPATH/libatk-1.0.so.0
    - $RPATH/libatk-bridge-2.0.so.0
    - $RPATH/libgio-2.0.so.0
    - $RPATH/libxkbcommon.so.0
    - $RPATH/libX11.so.6
    - $RPATH/libXcomposite.so.1
    - $RPATH/libXdamage.so.1
    - $RPATH/libXext.so.6
    - $RPATH/libXfixes.so.3
    - $RPATH/libXrandr.so.2
    - $RPATH/libasound.so.2
    - $RPATH/libcups.so.2
    - $RPATH/libatspi.so.0
    - $RPATH/libxshmfence.so.1
    - $RPATH/libjawt.so
    - $RPATH/libXrender.so.1
    - $RPATH/libXtst.so.6
    - $RPATH/libXi.so.6
    - $RPATH/libXxf86vm.so.1
    - $RPATH/libXcursor.so.1
    - $RPATH/libstdc++.so.6
    - $RPATH/libjvm.dylib               # [osx]
    - $RPATH/libjawt.dylib              # [osx]
    - $RPATH/libpangoft2-1.0.so.0       # [linux and aarch64]
    - $RPATH/libgtk-x11-2.0.so.0        # [linux and aarch64]
    - $RPATH/libgdk-x11-2.0.so.0        # [linux and aarch64]
    - $RPATH/libgdk_pixbuf-2.0.so.0     # [linux and aarch64]
    - $RPATH/libgthread-2.0.so.0        # [linux and aarch64]
    - $RPATH/ld-linux-x86-64.so.2       # [linux and (aarch64 or s390x or ppc64le)]
    - $RPATH/libgtk-3.so.0              # [linux and aarch64]
    - $RPATH/libgdk-3.so.0              # [linux and aarch64]
    - $RPATH/libavcodec-ffmpeg.so.56    # [linux and aarch64]
    - $RPATH/libavformat-ffmpeg.so.56   # [linux and aarch64]
    - $RPATH/libGL.so.1                 # [linux and aarch64]
    - $RPATH/libgmodule-2.0.so.0        # [linux and aarch64]
    - /*/*/*/*/*/*/*/Frameworks/JavaNativeFoundation.framework/JavaNativeFoundation  # [osx and arm64]
    - /*/*/*/*/*/*/Frameworks/JavaRuntimeSupport.framework/Versions/A/JavaRuntimeSupport  # [osx and x86_64]
    - Library\bin\VCRUNTIME140.dll      # [win]
    - Library\bin\VCRUNTIME140_1.dll      # [win]
    - Library\bin\bin\VCRUNTIME140.dll  # [win]
    - Library\bin\bin\VCRUNTIME140_1.dll  # [win]
    - Library\bin\MSVCP140.dll          # [win]
    - Library\bin\bin\MSVCP140.dll      # [win]
    - $RPATH/jvm.dll                    # [win]
    - $RPATH/libcef.dll  # [win]
    - $RPATH/chrome_elf.dll  # [win]
    - $RPATH/api-ms-win-core-winrt-string-l1-1-0.dll  # [win]
    - $RPATH/api-ms-win-core-realtime-l1-1-1.dll  # [win]
    - $RPATH/api-ms-win-core-winrt-l1-1-0.dll  # [win]
    - $RPATH/libwayland-client.so.0
    - $RPATH/libwayland-cursor.so.0

requirements:
  build:
    - {{ compiler('cxx') }}   # [not win]
    - zip                     # [linux]
  host:
    - cairo                   # [linux]
    - dbus                    # [linux]
    - expat                   # [linux]
    - freetype                # [linux]
    - glib                    # [linux]
    - libxcb                  # [linux]
    - pango                   # [linux]
    - zlib                    # [unix]
  run:
    - cairo                   # [linux]
    - dbus                    # [linux]
    - expat                   # [linux]
    - freetype                # [linux]
    - glib                    # [linux]
    - libxcb                  # [linux]
    - pango                   # [linux]
 
test:
  requires:
    - {{ compiler('c') }}
  files:
    - test-jni     # [not win]
    - test-jni.sh  # [not win]
    - test-nio
  # commands:
    # - java -version
    # - ./test-jni.sh                                # [not win]
    # - conda inspect linkages -p ${PREFIX} openjdk  # [linux]
    # - conda inspect objects -p ${PREFIX} openjdk   # [osx]

about:
  home: https://github.com/JetBrains/JetBrainsRuntime
  license: GPL-2.0-only
  license_family: GPL
  license_url: "https://raw.githubusercontent.com/JetBrains/JetBrainsRuntime/refs/tags/jdk-21+35/LICENSE"
  summary: The JetBrains Runtime OpenJDK build.
  description: |
    JetBrains Runtime is a runtime environment for running
    IntelliJ Platform based products on Windows, Mac OS X, and Linux
  dev_url: https://github.com/JetBrains/JetBrainsRuntime
  doc_url: https://openjdk.org/guide/

extra:
  recipe-maintainers:
    - johanneskoester
    - mingwandroid
    - sodre
