# Based on recipes from birdhouse and anaconda channel.

{% set name = "openjdk" %}
{% set version = "8.0.152" %}
{% set ver_parts = version.split('.') %}
{% set intellij_build = "1024.6" %}
{% set build_number = 0 %}
{% set sha256_osx = "c4c7daf4d68cc4a98a7e8e028ecbb6216203c73cab4f235671b7ac6303d38017" %}
{% set sha256_linux_64 = "7e6284739c0e5b7142bc7a9adc61ced70dc5bb26b130b582b18e809013bcb251" %}
{% set sha256_linux_32 = "7e6284739c0e5b7142bc7a9adc61ced70dc5bb26b130b582b18e809013bcb251" %}
{% set sha256_win_64 = "f1d9d3341ef7c8c9baff3597953e99a6a7c64f8608ee62c03fdd7574b7655c02" %}
{% set sha256_win_32 = "f1d9d3341ef7c8c9baff3597953e99a6a7c64f8608ee62c03fdd7574b7655c02" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://bintray.com/jetbrains/intellij-jdk/download_file?file_path=jbsdk{{ ver_parts[0] }}u{{ ver_parts[2] }}b{{ intellij_build }}_osx_x64.tar.gz      # [osx]
  fn: jbsdk{{ ver_parts[0] }}u{{ ver_parts[2] }}b{{ intellij_build }}_osx_x64.tar.gz                                                                          # [osx]
  url: https://bintray.com/jetbrains/intellij-jdk/download_file?file_path=jbsdk{{ ver_parts[0] }}u{{ ver_parts[2] }}b{{ intellij_build }}_linux_x64.tar.gz    # [linux64]
  fn: jbsdk{{ ver_parts[0] }}u{{ ver_parts[2] }}b{{ intellij_build }}_linux_x64.tar.gz                                                                        # [linux64]
  url: https://bintray.com/jetbrains/intellij-jdk/download_file?file_path=jbsdk{{ ver_parts[0] }}u{{ ver_parts[2] }}b{{ intellij_build }}_linux_x86.tar.gz    # [linux32]
  fn: jbsdk{{ ver_parts[0] }}u{{ ver_parts[2] }}b{{ intellij_build }}_linux_x86.tar.gz                                                                        # [linux32]
  url: https://bintray.com/jetbrains/intellij-jdk/download_file?file_path=jbsdk{{ ver_parts[0] }}u{{ ver_parts[2] }}b{{ intellij_build }}_windows_x64.tar.gz  # [win64]
  fn: jbsdk{{ ver_parts[0] }}u{{ ver_parts[2] }}b{{ intellij_build }}_windows_x64.tar.gz                                                                      # [win64]
  url: https://bintray.com/jetbrains/intellij-jdk/download_file?file_path=jbsdk{{ ver_parts[0] }}u{{ ver_parts[2] }}b{{ intellij_build }}_windows_x86.tar.gz  # [win32]
  fn: jbsdk{{ ver_parts[0] }}u{{ ver_parts[2] }}b{{ intellij_build }}_windows_x86.tar.gz                                                                      # [win32]
  sha256: {{ sha256_osx }}       # [osx]
  sha256: {{ sha256_linux_64 }}  # [linux64]
  sha256: {{ sha256_linux_32 }}  # [linux32]
  sha256: {{ sha256_win_64 }}    # [win64]
  sha256: {{ sha256_win_32 }}    # [win32]

build:
  number: {{ build_number }}
  track_features:
    - openjdk
  rpath:
    - lib
    - jre/lib

requirements:
  build:
    - curl


test:
  files:
    - test-jni     # [not win]
    - test-jni.sh  # [not win]
    - test-nio
  commands:
    - java -version
    - ./test-jni.sh                                # [not win]
    - conda inspect linkages -p ${PREFIX} openjdk  # [linux]
    - conda inspect objects -p ${PREFIX} openjdk   # [osx]

about:
  home: https://bintray.com/jetbrains/intellij-jdk
  license: GPLv2
  summary: The JetBrains Runtime OpenJDK build.
  description: |
    JetBrains Runtime is a runtime environment for running
    IntelliJ Platform based products on Windows, Mac OS X, and Linux

extra:
  recipe-maintainers:
    - johanneskoester
    - mingwandroid
    - sodre
