{% set name = "openjdk" %}
{% set version = "11.0.27" %}
{% set build = "6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/adoptium/temurin11-binaries/releases/download/jdk-{{ version }}+{{ build }}/OpenJDK11U-jdk_aarch64_mac_hotspot_{{ version }}_{{ build }}.tar.gz    # [osx and arm64]
    sha256: 780ae402dcd93fea0fee10d02dcd0a0b72cb7298f2ef4dddbad4d54c31a40a4d                                                                                                   # [osx and arm64]
  - url: https://github.com/adoptium/temurin11-binaries/releases/download/jdk-{{ version }}+{{ build }}/OpenJDK11U-jdk_x64_mac_hotspot_{{ version }}_{{ build }}.tar.gz        # [osx and x86_64]
    sha256: 805d225d46eab5702bf2f654856d846f426bebf6f143e5f06c8b1397855252e5                                                                                                   # [osx and x86_64]
  - url: https://github.com/adoptium/temurin11-binaries/releases/download/jdk-{{ version }}+{{ build }}/OpenJDK11U-jdk_aarch64_linux_hotspot_{{ version }}_{{ build }}.tar.gz  # [linux and aarch64]
    sha256: 4decd2e5caf4667144091cf723458b14148dc990730b3ecb34bba5eb1aa4ad5d                                                                                                   # [linux and aarch64]
  - url: https://github.com/adoptium/temurin11-binaries/releases/download/jdk-{{ version }}+{{ build }}/OpenJDK11U-jdk_x64_linux_hotspot_{{ version }}_{{ build }}.tar.gz      # [linux and x86_64]
    sha256: dc6136eaa8c1898cbf8973bb1e203e1f653f4c9166be0f5bebe0b02c5f3b5ae3                                                                                                   # [linux and x86_64]
  - url: https://github.com/adoptium/temurin11-binaries/releases/download/jdk-{{ version }}+{{ build }}/OpenJDK11U-jdk_x64_windows_hotspot_{{ version }}_{{ build }}.zip       # [win64]
    sha256: 8503478995c81926db7154e3fbf3fce3ea214b1062c0a3391db52b0798640f5c                                                                                                   # [win64]
  - url: https://github.com/dejavu-fonts/dejavu-fonts/releases/download/version_2_37/dejavu-fonts-ttf-2.37.zip                                                                 # [linux]
    sha256: 7576310b219e04159d35ff61dd4a4ec4cdba4f35c00e002a136f00e96a908b0a                                                                                                   # [linux]
    folder: fonts                                                                                                                                                              # [linux]

build:
  number: 0
  binary_relocation: False  # [osx and x86_64]
  ignore_run_exports:
    - libstdcxx-ng  # [linux]
  missing_dso_whitelist:
    # jvm is discoverable under $RPATH/bin/server/...
    - $RPATH/libjvm.so               # [linux]
    - $RPATH/libjvm.dylib            # [osx]
    - $RPATH/jvm.dll                 # [win]
    # linux system libs
    - $RPATH/libnss3.so              # [linux]
    - $RPATH/libdrm.so.2             # [linux]
    - $RPATH/libgbm.so.1             # [linux]
    - $RPATH/libnssutil3.so          # [linux]
    - $RPATH/libsmime3.so            # [linux]
    - $RPATH/libnspr4.so             # [linux]
    - $RPATH/libatk-1.0.so.0         # [linux]
    - $RPATH/libatk-bridge-2.0.so.0  # [linux]
    - $RPATH/libxkbcommon.so.0       # [linux]
    - $RPATH/libX11.so.6             # [linux]
    - $RPATH/libXcomposite.so.1      # [linux]
    - $RPATH/libXdamage.so.1         # [linux]
    - $RPATH/libXext.so.6            # [linux]
    - $RPATH/libXfixes.so.3          # [linux]
    - $RPATH/libXrandr.so.2          # [linux]
    - $RPATH/libasound.so.2          # [linux]
    - $RPATH/libcups.so.2            # [linux]
    - $RPATH/libatspi.so.0           # [linux]
    - $RPATH/libXrender.so.1         # [linux]
    - $RPATH/libXtst.so.6            # [linux]
    - $RPATH/libXi.so.6              # [linux]
    - $RPATH/libXxf86vm.so.1         # [linux]
    - $RPATH/libXcursor.so.1         # [linux]
    # osx-64 system libs
    - /*/*/*/*/*/*/Frameworks/JavaRuntimeSupport.framework/Versions/A/JavaRuntimeSupport             # [osx and x86_64]
    - /System/Library/Frameworks/UniformTypeIdentifiers.framework/Versions/A/UniformTypeIdentifiers  # [osx and x86_64]
    # windows system libs
    - $RPATH/api-ms-win-core-winrt-string-l1-1-0.dll  # [win]
    - $RPATH/api-ms-win-core-realtime-l1-1-1.dll      # [win]
    - $RPATH/api-ms-win-core-winrt-l1-1-0.dll         # [win]
    - $RPATH/api-ms-win-shcore-scaling-l1-1-1.dll     # [win]
    - $RPATH/api-ms-win-power-base-l1-1-0.dll         # [win]
    - $RPATH/api-ms-win-power-setting-l1-1-0.dll      # [win]

requirements:
  build:
    # Needed for c/c++ runtime exports
    - {{ compiler('cxx') }}    # [not osx]
  host:
    - freetype {{ freetype }}  # [linux]
    - xorg-libx11              # [linux]
    - xorg-libxrender          # [linux]
    - xorg-libxext             # [linux]

test:
  downstreams:
    - jpype1
  requires:
    - {{ compiler('c') }}
  files:
    - test-jni     # [not win]
    - test-jni.sh  # [not win]
    - test-nio
    - test-awt

about:
  home: https://github.com/JetBrains/JetBrainsRuntime
  license: GPL-2.0-only
  license_family: GPL
  license_url: "https://raw.githubusercontent.com/JetBrains/JetBrainsRuntime/refs/tags/jdk-17.0.14+7/LICENSE"
  summary: The JetBrains Runtime OpenJDK build.
  description: |
    JetBrains Runtime is a runtime environment for running
    IntelliJ Platform based products on Windows, Mac OS X, and Linux
  dev_url: https://github.com/JetBrains/JetBrainsRuntime
  doc_url: https://openjdk.org/guide/

extra:
  recipe-maintainers:
    - johanneskoester
    - mingwandroid
    - sodre
